model: ECAPA_TDNN
C: 1024
nOut: 192
batch_size: 1
trainfunc: aamsoftmax
max_seg_per_spk: 10
augment: False
youtube_path: data/MSV_Youtube_data/vi
save_file: data/MSV_Youtube_data/clustering_for_all/train_list_fr_all.txt
initial_model: output/ecapa/model/model000000034.model