model: ECAPA_TDNN
C: 1024
nOut: 192
nClasses: 96
batch_size: 64
trainfunc: aamsoftmax
max_seg_per_spk: 40000
augment: True
max_epoch: 20
save_path: output/vietnam_finetuning_1
train_list: data/MSV_CommonVoice_data/metadata/train_list_vi.txt
train_path: data/MSV_CommonVoice_data/vi/clips
test_list: data/Test/veri_test2.txt
test_path: data/Test/wav