model: ResNetSE34V2
encoder_type: ASP
trainfunc: angleproto
nClasses: 1015
batch_size: 16
max_seg_per_spk: 1000
augment: True
max_epoch: 2
save_path: output/SEResNet34_ASP_AAM
train_list: data/metadata/train/training_metadata.txt
train_path: ./
test_list: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1/data/metadata/test/sample_test_pairs_with_label.txt
test_path: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1/data/test/sv_vlsp_2021/public_test/competition_public_test
musan_path: data/musan_augment
rir_path: data/rirs_noises
output_path: output/testing_results/public_test