model: ECAPA_TDNN
C: 1024
nOut: 192
nClasses: 96
batch_size: 32
trainfunc: aamsoftmax
max_seg_per_spk: 500
augment: True
max_epoch: 10
save_path: output/angleproto_common/
train_list: data/MSV_CommonVoice_data/metadata/train_list_vi.txt
train_path: data/MSV_CommonVoice_data/vi/clips/
test_list: data/Test/eval_list.tsv
test_path: data/MSV_CommonVoice_data/vi/clips/